config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  get "search" => "searches#search"

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :index, :show]

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence:true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @comment = current_user.book_comments.new(book_comment_params)
    @comment.book_id = @book.id
    @comment.save
      render 'book_comments/index'
  end

  def destroy
    @book = Book.find(params[:book_id])
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    render 'book_comments/index'
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_book_comments.html.erb
<table>
  <tbody>
    <% book.book_comments.each do |book_comment| %>
    <tr>

      <td>
        <%= link_to user_path(book_comment.user) do %>
          <%= image_tag book_comment.user.get_profile_image, size:"100x100" %><br>
          <%= book_comment.user.name %>
        <% end %>
      </td>
      <td><%= book_comment.comment %></td>
      <td>
        <% if book_comment.user == current_user %>
          <%= link_to "Destroy", book_book_comment_path(book, book_comment), method: :delete, remote: true, data: {"turbolinks" => false},class: "btn btn-sm btn-danger pull-right" %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/book_comments/_counter.html.erb
コメント数: <%= book.book_comments.count %>

app/views/book_comments/_form.html.erb
<%= form_with(model: [book, book_comment], local: false) do |f| %>
  <%= f.text_area :comment, rows:'5', placeholder: "コメントをここに", class:'w-100' %>
  <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right"%>
<% end %>

app/views/book_comments/_index.html.erb
<table>
  <tbody>
    <% @book.book_comments.each do |book_comment| %>
    <tr>

      <td>
        <%= link_to user_path(book_comment.user) do %>
          <%= image_tag book_comment.user.get_profile_image, size:"100x100" %><br>
          <%= book_comment.user.name %>
        <% end %>
      </td>
      <td><%= book_comment.comment %></td>
      <td>
        <% if book_comment.user == current_user %>
          <%= link_to "Destroy", book_book_comment_path(book, book_comment), method: :delete, class: "btn btn-sm btn-danger pull-right" %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/book_comments/create.js.erb
$("#comments_area").html("<%= j(render 'book_comments/book_comments', book: @book, comment: @comment) %>");

$("textarea").val('');

app/views/book_comments/index.js.erb
$(".book-comments-counter").html("<%= j(render 'book_comments/counter', book: @book, comment: @comment) %>");
$("#comments_area").html("<%= j(render 'book_comments/book_comments', book: @book, comment: @comment) %>");
$("textarea").val('');